### PR TITLE
Ft login page 161578378

### PR DESCRIPTION
**Pull request by Bakley**
#### What does this PR do?
Built the login pages for the users

#### Description of Task to be completed?
All works finished

#### Any background context you want to provide?
User login forms

#### What are the relevant pivotal tracker stories?
#161578378

### CODE REVIEW

**Comment by ChegeBryan** [comment]
You could leave a screenshot of the UI its easier without me having to clone your repo.

**Comment by SimonAwiti** [comment]
Add screenshots and describe your topics well

**Comment by kelvinndmo** [comment]
add screenshots please

**Comment by Bakley** [comment]
Okay guys thanks will add the screenshots

**Pull request merged**
